### PR TITLE
Added new parser to get food buff data from xivdb

### PR DESCRIPTION
**Pull request by Ermad**
Added new parser for food buff data to be used for with doxxx/ffxiv-craft-opt-web#172.

### CODE REVIEW

**Comment by Ermad** [comment]
Still need to double check everything, make sure the filter is getting all the recipes etc, but looks ready besides that.

**Comment by doxxx** [comment]
Awesome! Thanks for doing this!

**Comment by Ermad** [comment]
Also added support for it scraping Medicines. Though for some weird reason XIVDB has wrong data for Potion (http://xivdb.com/item/4551/potion) saying it has +Craftsmanship on it

**Comment by doxxx** [comment]
I've emailed the XIVDB developer about that item.

**Comment by doxxx** [comment]
Oh yeah, just remembered this -- could you look at getting the item names in the different languages?

**Pull request merged**
